/**
 * The three properties that make FR-E004's "lossless" a checked claim (ART-27).
 *
 * The word only means something if it names a dimension. This suite fixes three, and — in the
 * last case — the one dimension where compression is deliberately *lossy*, so the boundary of
 * the claim is in the test file rather than only in the prose:
 *
 * 1. **Exact partition** — the retained corpus and the digests' sources cover the input memory
 *    ids exactly once between them. AC#1: nothing is dropped, duplicated or invented.
 * 2. **Round trip** — expanding a compression against its corpus returns the input verbatim.
 * 3. **Recall preservation** — the FR-E003 retriever run over the compressed corpus returns
 *    every retained memory it would have returned uncompressed, at the same or better rank, for
 *    every limit. AC#3 follows, because every high-importance memory is retained.
 *
 * These run against the real `retrieveAuthorizedMemories`, not a stand-in. A compression that
 * preserved recall only against a model of the retriever would preserve nothing.
 */

import type { CharacterMemoryRecord } from '../canon/model';
import {
  compressCharacterMemories,
  expandCompressedMemories,
  HIGH_IMPORTANCE_RETENTION,
  type MemoryCompressionRequest,
  type MemoryEventContext,
} from './memoryCompression';
import { MAX_RETRIEVED_MEMORIES, retrieveAuthorizedMemories } from './memoryRetrieval';

const OWNER = 'ana';
const COMPANIONS = ['bo', 'cy', 'dee'];
const LOCATIONS = ['mill', 'quay', 'chapel'];
const ARCS = ['arc-flood', 'arc-debt'];
const READINGS = [
  'the mill is unsafe',
  'bo is hiding something',
  'the quay floods every spring',
  'nobody will say who paid',
];

/**
 * Thirty memories, one per world day, generated by index arithmetic.
 *
 * Arithmetic rather than a random generator on purpose: a property that only holds for the seed
 * someone happened to run is not a property. The moduli are coprime with each other and with the
 * corpus length so importance, tone, companion, location and arc membership vary independently
 * — the corpus covers both sides of the retention floor and both retention reasons.
 */
const CORPUS: readonly CharacterMemoryRecord[] = Array.from({ length: 30 }, (_, index) => {
  const worldDay = index + 1;
  const eventId = `event-${String(index).padStart(2, '0')}`;
  return {
    memoryId: `${eventId}:memory:0`,
    characterId: OWNER,
    content: `${READINGS[index % READINGS.length]} near the ${LOCATIONS[index % 3]} on day ${worldDay}`,
    interpretation: READINGS[index % READINGS.length],
    importance: (index % 10) / 10,
    emotionalWeight: ((index % 7) - 3) / 3,
    confidence: ((index % 5) + 1) / 5,
    visibility: 'private' as const,
    sourceEventId: eventId,
    createdAt: { worldDay, timeSlot: 'morning' as const, eventId },
  };
});

const EVENT_CONTEXTS: readonly MemoryEventContext[] = CORPUS.map((memory, index) => ({
  eventId: memory.sourceEventId,
  participantCharacterIds: index % 5 === 0 ? [OWNER] : [OWNER, COMPANIONS[index % 3]],
  ...(index % 7 === 0 ? {} : { locationId: LOCATIONS[index % 3] }),
  arcIds: index % 4 === 0 ? [ARCS[index % 2]] : [],
}));

const COMPRESSION_REQUEST: MemoryCompressionRequest = {
  characterId: OWNER,
  // Day 33 with a ten-day horizon puts the corpus astride both retention reasons: days 24-30 are
  // recent, days 1-23 are old and survive only on importance.
  now: { worldDay: 33, timeSlot: 'night' },
  horizonDays: 10,
  eventContexts: EVENT_CONTEXTS,
};

/** Retrieval requests chosen to disagree with each other about what matters. */
const SCENARIOS = [
  { query: 'mill unsafe', now: { worldDay: 33, timeSlot: 'night' as const }, arcRelevantEventIds: [] },
  { query: 'quay floods spring', now: { worldDay: 12, timeSlot: 'noon' as const }, arcRelevantEventIds: ['event-04', 'event-08'] },
  { query: 'who paid', now: { worldDay: 33, timeSlot: 'morning' as const }, arcRelevantEventIds: ['event-00'] },
  { query: '', now: { worldDay: 33, timeSlot: 'night' as const }, arcRelevantEventIds: [] },
];

const RESULT = compressCharacterMemories(CORPUS, COMPRESSION_REQUEST);
const RETAINED_IDS = new Set(RESULT.retainedMemories.map((memory) => memory.memoryId));

function retrieve(
  corpus: readonly CharacterMemoryRecord[],
  scenario: (typeof SCENARIOS)[number],
  limit: number,
): CharacterMemoryRecord[] {
  return retrieveAuthorizedMemories({ [OWNER]: [...corpus] }, {
    targetCharacterId: OWNER,
    requester: { type: 'character', characterId: OWNER },
    limit,
    ...scenario,
  }).memories;
}

describe('FR-E004 lossless properties', () => {
  it('compresses the fixture at all — the properties below would be vacuous otherwise', () => {
    expect(RESULT.candidateCount).toBe(CORPUS.length);
    expect(RESULT.foldedMemoryIds.length).toBeGreaterThan(0);
    expect(RESULT.retainedMemories.length).toBeGreaterThan(0);
    expect(RESULT.retainedMemories.length).toBeLessThan(CORPUS.length);
    expect(new Set(RESULT.digests.map((digest) => digest.kind)))
      .toEqual(new Set(['impression', 'belief', 'relationship', 'arc', 'location']));
  });

  it('AC#1: partitions the corpus exactly — retained and folded, disjoint and total', () => {
    const digested = RESULT.digests.flatMap((digest) => digest.sourceMemoryIds);
    const covered = [...new Set(digested)].sort();

    expect(covered).toEqual(RESULT.foldedMemoryIds);
    expect([...RETAINED_IDS].filter((id) => RESULT.foldedMemoryIds.includes(id))).toEqual([]);
    expect([...RETAINED_IDS, ...RESULT.foldedMemoryIds].sort())
      .toEqual(CORPUS.map((memory) => memory.memoryId).sort());
  });

  it('AC#1: the impression digest alone is total, which is why the union above can be', () => {
    // Relationship, arc and location digests are conditional on the event carrying the fact they
    // key on, so none of them can carry the coverage guarantee. The impression is the one kind
    // every folded memory reaches unconditionally; if it ever stops being total, the union check
    // above is measuring an accident.
    const impression = RESULT.digests.find((digest) => digest.kind === 'impression')!;

    expect(impression.sourceMemoryIds).toEqual(RESULT.foldedMemoryIds);
    expect(impression.subject).toBe(OWNER);
  });

  it('AC#1: every digest cites Accepted Events that exist in the corpus', () => {
    const eventIds = new Set(CORPUS.map((memory) => memory.sourceEventId));
    for (const digest of RESULT.digests) {
      expect(digest.sourceEventIds.every((eventId) => eventIds.has(eventId))).toBe(true);
      expect(digest.sourceMemoryIds.length).toBe(digest.memoryCount);
    }
  });

  it('round-trips: expanding the compression returns the corpus verbatim', () => {
    expect(expandCompressedMemories(RESULT, CORPUS)).toEqual([...CORPUS]);
  });

  it('AC#3: every high-importance memory survives compression verbatim', () => {
    const important = CORPUS.filter((memory) => memory.importance >= HIGH_IMPORTANCE_RETENTION);

    expect(important.length).toBeGreaterThan(0);
    for (const memory of important) {
      expect(RESULT.retainedMemories).toContainEqual(memory);
    }
  });

  it('AC#3: retrieval over the compressed corpus loses no retained memory, at any limit', () => {
    let comparisons = 0;
    let highImportanceComparisons = 0;
    for (const scenario of SCENARIOS) {
      for (let limit = 1; limit <= MAX_RETRIEVED_MEMORIES; limit += 1) {
        const full = retrieve(CORPUS, scenario, limit);
        const compressed = retrieve(RESULT.retainedMemories, scenario, limit);
        const rankIn = new Map(compressed.map((memory, rank) => [memory.memoryId, rank]));
        full.forEach((memory, fullRank) => {
          if (!RETAINED_IDS.has(memory.memoryId)) return;
          const compressedRank = rankIn.get(memory.memoryId);
          expect(compressedRank).toBeDefined();
          // Same or better rank: dropping candidates can only promote a survivor, never demote
          // it, because every FR-E003 factor scores one memory without reference to the others.
          expect(compressedRank!).toBeLessThanOrEqual(fullRank);
          // And the record itself, not a summary standing in for it.
          expect(compressed[compressedRank!]).toEqual(memory);
          comparisons += 1;
          if (memory.importance >= HIGH_IMPORTANCE_RETENTION) highImportanceComparisons += 1;
        });
      }
    }
    expect(comparisons).toBeGreaterThan(100);
    expect(highImportanceComparisons).toBeGreaterThan(20);
  });

  it('states the loss: a folded memory leaves the retrieval corpus but stays recoverable', () => {
    const scenario = SCENARIOS[0];
    const full = retrieve(CORPUS, scenario, MAX_RETRIEVED_MEMORIES);
    const dropped = full.filter((memory) => !RETAINED_IDS.has(memory.memoryId));

    expect(dropped.length).toBeGreaterThan(0);
    const compressed = retrieve(RESULT.retainedMemories, scenario, MAX_RETRIEVED_MEMORIES);
    for (const memory of dropped) {
      expect(compressed.map((record) => record.memoryId)).not.toContain(memory.memoryId);
      // Gone from cognition, not from the record: the id is in a digest, and the digest resolves.
      expect(RESULT.digests.some((digest) => digest.sourceMemoryIds.includes(memory.memoryId)))
        .toBe(true);
      expect(expandCompressedMemories(RESULT, CORPUS)).toContainEqual(memory);
    }
  });

  it('compressing an already-compressed corpus is a fixed point', () => {
    // Folding twice must not fold further, or "old" would be relative to the last run rather
    // than to world time and a character would keep quietly losing memories on every pass.
    const again = compressCharacterMemories(RESULT.retainedMemories, {
      ...COMPRESSION_REQUEST,
      eventContexts: EVENT_CONTEXTS.filter(
        (context) => RESULT.retainedMemories.some((memory) => memory.sourceEventId === context.eventId),
      ),
    });

    expect(again.foldedMemoryIds).toEqual([]);
    expect(again.digests).toEqual([]);
    expect(again.retainedMemories).toEqual(RESULT.retainedMemories);
  });
});
